FROM python:3.10.11-slim

WORKDIR /app

COPY requirements.txt requirements.txt

RUN apt-get update && \
apt-get install -y libgomp1 && \
pip install --no-cache-dir -r requirements.txt && \
apt-get clean

EXPOSE 5000

COPY . .

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "wsgi:app"]